-- MySQL Script generated by MySQL Workbench
-- Wed Aug 18 17:47:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdsabios
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bdsabios` ;

-- -----------------------------------------------------
-- Schema bdsabios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdsabios` DEFAULT CHARACTER SET utf8 ;
USE `bdsabios` ;

-- -----------------------------------------------------
-- Table `bdsabios`.`Socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsabios`.`Socio` (
  `idSocio` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Función` VARCHAR(45) NULL,
  PRIMARY KEY (`idSocio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsabios`.`Aliado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsabios`.`Aliado` (
  `idAliado` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NULL,
  `Profesion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAliado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsabios`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsabios`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdsabios`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdsabios`.`Servicio` (
  `idServicio` INT NOT NULL,
  `IdCiliente` INT NOT NULL,
  `IdAliado` INT NULL,
  `IdSocio` INT NULL,
  `Valor` INT NOT NULL,
  PRIMARY KEY (`idServicio`),
  INDEX `idSocio_idx` (`IdSocio` ASC) VISIBLE,
  INDEX `IdAliado_idx` (`IdAliado` ASC) VISIBLE,
  INDEX `IdClientes_idx` (`IdCiliente` ASC) VISIBLE,
  CONSTRAINT `idSocio`
    FOREIGN KEY (`IdSocio`)
    REFERENCES `bdsabios`.`Socio` (`idSocio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdAliado`
    FOREIGN KEY (`IdAliado`)
    REFERENCES `bdsabios`.`Aliado` (`idAliado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdClientes`
    FOREIGN KEY (`IdCiliente`)
    REFERENCES `bdsabios`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
